# Đường dẫn kết nối tới MS SQL Server
spring.datasource.url=jdbc:sqlserver://KsDesktop:1433;databaseName=student_management;encrypt=false;trustServerCertificate=true

# Tài khoản đăng nhập SQL Server
spring.datasource.username=sa
spring.datasource.password=123456789

# Định danh Driver của Microsoft
spring.datasource.driver-class-name=com.microsoft.sqlserver.jdbc.SQLServerDriver

# Không để Spring tự động tạo/xóa bảng
spring.jpa.hibernate.ddl-auto=none

# Cổng chạy ứng dụng Java
server.port=8080

spring.main.headless=false